export enum CONSUMIBLE_FORMAT_DATA_BASE {
  NOMBRE = 'nombre',
  CATEGORIA = 'categoria',
  CANTIDAD = 'cantidad',
  CANTIDAD_MINIMA = 'cantidadMinima',
  FABRICANTE = 'fabricante',
  MODELO = 'modelo',
  PROVEEDOR = 'proveedor',
  COSTO = 'costo',
  NUMERO_DE_FACTURA = 'numeroFactura',
  FECHA_DE_COMPRA = 'fechaCompra',
  OBSERVACIONES = 'observaciones',
}

export enum CONSUMIBLE_FORMAT_EXCEL_HEADERS {
  NOMBRE = 'NOMBRE',
  CATEGORIA = 'CATEGORIA',
  CANTIDAD = 'CANTIDAD',
  CANTIDAD_MINIMA = 'CANTIDAD MINIMA',
  FABRICANTE = 'FABRICANTE',
  MODELO = 'MODELO',
  PROVEEDOR = 'PROVEEDOR',
  COSTO = 'VALOR',
  NUMERO_DE_FACTURA = 'NUMERO DE FACTURA',
  FECHA_DE_COMPRA = 'FECHA DE COMPRA',
  OBSERVACIONES = 'OBSERVACIONES',
}
