export enum CONSUMIBLE_FORMAT_DATA_BASE {
  NOMBRE = 'NOMBRE',
  CATEGORIA = 'CATEGORIA',
  CANTIDAD = 'CANTIDAD',
  CANTIDAD_MINIMA = 'CANTIDAD_MINIMA',
  FABRICANTE = 'FABRICANTE',
  MODELO = 'MODELO',
  PROVEEDOR = 'PROVEEDOR',
  VALOR = 'VALOR',
  NUMERO_DE_FACTURA = 'NUMERO_DE_FACTURA',
  FECHA_DE_COMPRA = 'FECHA_DE_COMPRA',
  OBSERVACIONES = 'OBSERVACIONES',
}

export enum CONSUMIBLE_FORMAT_EXCEL_HEADERS {
  NOMBRE = 'NOMBRE',
  CATEGORIA = 'CATEGORIA',
  CANTIDAD = 'CANTIDAD',
  CANTIDAD_MINIMA = 'CANTIDAD MINIMA',
  FABRICANTE = 'FABRICANTE',
  MODELO = 'MODELO',
  PROVEEDOR = 'PROVEEDOR',
  VALOR = 'VALOR',
  NUMERO_DE_FACTURA = 'NUMERO DE FACTURA',
  FECHA_DE_COMPRA = 'FECHA DE COMPRA',
  OBSERVACIONES = 'OBSERVACIONES',
}
